FROM node:22 AS build

WORKDIR /app

RUN git clone https://github.com/tommot20077/AudioToTextWeb.git source && \
    cd /app/source && \
    cp -r /app/source/* /app/ && \
    mkdir -p /app/temp && \
    cp /app/source/docker/config.ts /app/temp/config.ts && \
    rm -rf /app/source && \
    cd /app

RUN npm install

CMD ["npm", "run", "dev"]
